### ISSUE TITLE
Object metadata API cleanup

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#171]
We had a discussion on this today. This is related to this issue: https://github.com/mmtk/mmtk-core/issues/52

Our current interface about this (in the `ObjectModel` trait) is confusing:
* The `available byte` methods: to access the GC byte.
* The `available bits` methods: to access a few bits in the object metadata. The definition of which bits are available are quite vague. However, we use this method to store forwarding pointers.
* The `get_gc_byte()` and `GC_BYTE_OFFSET`:
  * `get_gc_byte()` returns a `&AtomicU8` for the available byte for GC. It could be in the header or in the side table.
  * `GC_BYTE_OFFSET` returns the offset for the available byte if it is in the object header.

The proposed new interface is:
* Have a `const GC_BYTE: bool`: whether the runtime provides a GC byte in the **header**. If true, MMTk will check `GC_BYTE_OFFSET` for its offset. Otherwise, MMTk will manage metadata (e.g. in a side table).
* Have a `const GC_BYTE_OFFSET: isize`: the offset if the runtime provides a GC byte in the header. 

This is under some assumptions:
* The runtime should only access live objects (no access dead objects or gap between objects).
* Objects for finalisation are not dead.

We should cleanup our API by doing the following:
1. Remove the `available bits` methods. If we write forwarding pointers in available bits, write them in the object instead. 
1. Remove the `available byte` methods. Replace them with `get_gc_byte()`.
1. Remove `get_gc_byte()` and replace with `GC_BYTE: bool` and `GC_BYTE_OFFSET: isize`. We can have assertions to make sure mmtk only works if `GC_BYTE` is true, as we are not going to implement side tables now.

**Comment by udesou** [comment]
Thanks @qinsoon and @javadamiri. I'm really looking forward to this. I've been struggling to get it for Mu, because I got confused with `GC_BYTE_OFFSET`, `get_gc_byte` and the `available_bits` methods. 
Also, FYI, I've noted that the method `set_forwarding_pointer` was not being called anywhere (unless it is, and I just didn't have the full picture of it).

**Comment by udesou** [comment]
By the way, I have just pushed a cleanup/fix to my fork of `mmtk-core` in https://github.com/udesou/mmtk-core-1/commit/51a49d2c51e766767a3154fa788ca51b3ca23434 that works for Mu's object model. 
I believe my solution may not be generic enough, since sometimes the header can be included in the object itself, but in any case I will share it here if it turns out to be helpful for you guys. My changes are essentially:
 - `GC_BYTE_OFFSET` is the offset (in bytes) from the beginning of the object itself (without the header). For example in Mu, this variable is set to -4 (header is 4 bytes, its first byte is the GC byte).
- When marking an object is forwarded I simply write `FORWARDED` to its GC byte, by calling `write_available_byte`. 
- `write_available_bits(object, val)` simply stores `val` inside `object` - perhaps the name is still misleading.
- `read_available_bits(object)` simply reads the content of object, i.e., the forwarded object. 

Note that this way I don't need to shift `FORWARDED` using `GC_BYTE_OFFSET`, and don't need the function `gc_byte::get_relative_offset`, which also got me confused.

Finally, this is how `object_model` looks like in Mu now: https://gitlab.anu.edu.au/mu/mu-impl-fast/-/blob/rust-2018/src/mmtk-gc/src/object_model.rs

**Comment by javadamiri** [comment]
> By the way, I have just pushed a cleanup/fix to my fork of `mmtk-core` in [udesou@51a49d2](https://github.com/udesou/mmtk-core-1/commit/51a49d2c51e766767a3154fa788ca51b3ca23434) that works for Mu's object model.
> I believe my solution may not be generic enough, since sometimes the header can be included in the object itself, but in any case I will share it here if it turns out to be helpful for you guys. My changes are essentially:
> 
> * `GC_BYTE_OFFSET` is the offset (in bytes) from the beginning of the object itself (without the header). For example in Mu, this variable is set to -4 (header is 4 bytes, its first byte is the GC byte).
> * When marking an object is forwarded I simply write `FORWARDED` to its GC byte, by calling `write_available_byte`.
> * `write_available_bits(object, val)` simply stores `val` inside `object` - perhaps the name is still misleading.
> * `read_available_bits(object)` simply reads the content of object, i.e., the forwarded object.
> 
> Note that this way I don't need to shift `FORWARDED` using `GC_BYTE_OFFSET`, and don't need the function `gc_byte::get_relative_offset`, which also got me confused.
> 
> Finally, this is how `object_model` looks like in Mu now: https://gitlab.anu.edu.au/mu/mu-impl-fast/-/blob/rust-2018/src/mmtk-gc/src/object_model.rs

Thanks for sharing this with us,
In my opinion, our object model is still not generic enough and we need to discuss some corner cases.
But overall, the final cleaned-up version will cover the model you used in your fork, only with slight name changes.

**Comment by qinsoon** [comment]
I believe this is done by the two PRs above. I am not aware of anything else we should do for this issue. I am closing this issue.
